### PR TITLE
Initial Commit- Completed Task 1

### PR DESCRIPTION
**Pull request by RinkiyaKeDad**
## CSoC Task 3 Submission

I have completed the following tasks

- [x] Basic endpoints
- [ ] Collaborator feature

Will be completing Task 2 soon and updating

### CODE REVIEW

**Comment by RinkiyaKeDad** [comment]
## CSoC Task 3 Submission

I have completed the following tasks

- [x] Basic endpoints
- [x] Collaborator feature

Completed Both Tasks. Ready For Review.

**Comment by nishantwrp** [comment]
Hi @RinkiyaKeDad, the swagger view didn't launch for me. There were errors. Please test your app before submitting it. I have updated your score based on your code. Here are some suggestions.
- `RetrieveUpdateDestroyAPIView` could be used in TodoDetail View
- Anyone is able to view and modify anyones todo. I mean there are no restrictions.
- I couldn't see the collaborator feature implemented properly.

**Comment by RinkiyaKeDad** [comment]
Hey @nishantwrp what exactly is the error you're getting? Cause I tested using Postman and all API routes including the collaborator feature worked. Also I got an authentication error when I didn't pass in the token which means that not anybody is able to access someone else's information contrary to what you experienced.

**Comment by RinkiyaKeDad** [comment]
Hi @nishantwrp , the api was working well and good when I tested using postman its just that the swagger view didn't load up cause I used 'name' instead of 'first_name' in the 'fields' of the UserSerializer. I haven't changed anything else in the code except that. Could you please try and check again if its working? Thanks a lot.

**Pull request closed without merging**
